### ISSUE TITLE
It's possible to use with Electron?

### ISSUE THREAD

**Issue by sergiopvilar** [sindresorhus/cocoa-dialog#1]
Hey, I would like to know if there's a way to use this module in Electron apps.

Thank you!

**Comment by sindresorhus** [comment]
You can use any Node.js module with Electron, including this one.

**Comment by sergiopvilar** [comment]
Just tested here and it seems a way different that in the README using the same options:
![Sample](http://d.pr/i/H1Gm.png)

**Comment by sindresorhus** [comment]
Ah yeah. Seems I forgot to do a required dependency bump before release. Fixed now.

**Comment by sergiopvilar** [comment]
Perfect! Thank you.
