### ISSUE TITLE
Deprecate in favor of cocoadialog?

### ISSUE THREAD

**Issue by markhalliwell** [sindresorhus/cocoa-dialog#2]
I'm actually one of the maintainers at https://github.com/mstratman/cocoadialog and had been creating my own Node.js wrapper locally for a while.

I finally published it recently and it's now available here: https://github.com/unicorn-fail/node-cocoadialog

I was just doing some surfing for marketing purposes and just saw this package.

I think it would make sense to deprecate this one.

Thoughts?

**Comment by SamVerschueren** [comment]
Why would it make sense?

**Comment by markhalliwell** [comment]
Because https://github.com/unicorn-fail/node-cocoadialog is a proper Node.js wrapper:

- Fully featured
  - Type completion in IDEs
  - Debugging
  - Events
  - Promises
  - Error handling (both Events and Promises)
- Extensive [API Documentation](https://unicorn-fail.github.io/node-cocoadialog/?api)
- [Examples](https://unicorn-fail.github.io/node-cocoadialog/?content=examples)

This project basically just wraps the shell command.

**Comment by markhalliwell** [comment]
Also because I plan on starting a new [cocoaDialog 4](https://github.com/mstratman/cocoadialog/milestone/9) version (based on Swift and newer techniques). So I'll be updating https://github.com/unicorn-fail/node-cocoadialog to coincide with those changes.

**Comment by sindresorhus** [comment]
I totally forgot to do this, but doesn't seem worth deprecating now as the references projects has not seen any activity in 3 years.
